<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net8.0</TargetFrameworks>
		<PackageTags>Taos;Data;ADO.NET;Entity Framework,;EF; Core;Data O/RM,;entity-framework-core;TDengine;IoTSharp;ORM</PackageTags>
		<Authors>Yanhong Ma</Authors>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageProjectUrl>https://github.com/IoTSharp/TaosConnector</PackageProjectUrl>

		<PackageIconUrl></PackageIconUrl>

		<RepositoryUrl>https://github.com/IoTSharp/TaosConnector</RepositoryUrl>

		<PackageReleaseNotes>IoTSharp.ORM.Taos   访问TDengine数据库的便捷ORM。</PackageReleaseNotes>

		<Copyright>Copyright © 2019-2026 IoTSharp All rights reserved.</Copyright>

		<Version>3.4.0</Version>

		<Platforms>AnyCPU;x64;x86</Platforms>
		<PackageIcon>logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\..\docs\logo.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\IoTSharp.Data.Taos\IoTSharp.Data.Taos.csproj" />
	</ItemGroup>

</Project>
